apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pbindal-tenant-pipeline-next-
  labels:
    appstudio.openshift.io/component: operator-next-index-4-17
spec:
  params:
    - name: release
      value: tekton-ecosystem-tenant/tektoncd-triggers-next-69tfz-8db3f6b-z9bxf
    - name: releasePlan
      value: tekton-ecosystem-tenant/tektoncd-triggers-next-rp
    - name: snapshot
      value: tekton-ecosystem-tenant/tektoncd-triggers-next-cgdwt
    - name: released_version
      value: 5.0.5
    - name: taskGitUrl
      value: https://github.com/openshift-pipelines/hack.git
    - name: taskGitRevision
      value: main
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/pramodbindal/demo
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline/release-pipeline.yaml

