#!/bin/bash

export KUBECONFIG=/tmp/eaas-kubeconfig
export INSECURE_SKIP_TLS_VERIFY=true
export CLUSTER_KUBECONFIG=/tmp/$CLUSTER_NAME-kubeconfig

cat $HOME/RedHat/kube/konflux > $KUBECONFIG

EAAS=eaas-spacerequest-grs5h-d5g9r
#EAAS=eaas-spacerequest-vznpn-pt4r5

oc get secret $EAAS -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
cat $CLUSTER_KUBECONFIG > $KUBECONFIG

PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')

echo "Cluster Phase : $PHASE"

while [ $PHASE = "ClusterInstalling" ];
do
  oc get cti
  sleep 30
  PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')
done

SECRET=$(oc get cti -o jsonpath='{.items[0].status.kubeconfig.name}')
echo "Found kubeconfig secret: $SECRET"

oc get secret $SECRET -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
echo "Wrote kubeconfig to $CLUSTER_KUBECONFIG"
cat $CLUSTER_KUBECONFIG > $KUBECONFIG

ARCH=$(oc get nodes -o jsonpath='{.items[0].metadata.labels.kubernetes\.io\/arch}')
echo $ARCH



