---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-operator
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster and deploys an Operator
    bundle from a Konflux snapshot.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: Namespace where the the Operator bundle will be deployed.
      name: NAMESPACE
      default: default
      type: string
  workspaces:
    - name: credentials
      secret:
        secretName: k8s-rosa
  tasks:
    - name: deploy-operator
      params:
        - name: bundleImage
          value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle:on-pr-50f60424789114acc5c6644cbea516e475c439d0
        - name: namespace
          value: "$(params.NAMESPACE)"
      taskSpec:
        params:
          - name: bundleImage
            type: string
          - name: namespace
            type: string
        volumes:
          - name: credentials
            emptyDir: { }
        steps:

          - name: operator-sdk-run-bundle
            image: quay.io/operator-framework/operator-sdk:latest
            env:
              - name: KUBECONFIG
                value: "$(workspaces.credentials.path)/rosa"
            args:
              - run
              - bundle
              - --namespace
              - "$(params.namespace)"
              - "$(params.bundleImage)"
              #            script: |
              #              set -x
              #              echo  "KUBECONFIG : $KUBECONFIG"
              #              ls -l ./workspace/credentials
              #              pwd
              #              cat $KUBECONFIG

