---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-operator-pipelines-e2e-tests-
  labels:
    appstudio.openshift.io/component: operator-main-bundle
spec:
  PipelineSpec:
    params:
      - description: Snapshot of the application
        name: SNAPSHOT
        default: '{"application":"operator-main","components":[{"name":"operator-main-bundle","containerImage":"quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle@sha256:27ef7cb02588c0a2230cde9aa0a1954ae276502a62c7ae71193e89973ee23f80","source":{"git":{"url":"https://github.com/openshift-pipelines/operator","revision":"298a17fb290d98f4eea9e68e81ad88d86f826a6d"}}},{"name":"operator-main-index","containerImage":"quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main-index@sha256:fa5c8db42bdef45b04c4d81a79a7e3d0c18d47e7caea0123a1fffce5a18dc6a5","source":{"git":{"url":"https://github.com/openshift-pipelines/operator.git","revision":"05f28fc598a01c35cd972f03ee19ba0c93944b1f","dockerfileUrl":"olm-catalog/openshift-pipelines/index/Dockerfile"}}},{"name":"operator-main-operator","containerImage":"quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:de5d8f6688f8f121e83cd0082505b1d0b3a590a3d86f427435c0d71f3db252c0","source":{"git":{"url":"https://github.com/openshift-pipelines/operator","revision":"570bcfb8310348417e9189f59dd1308f594ca76d","dockerfileUrl":"openshift/dockerfiles/operator.Dockerfile"}}},{"name":"operator-main-proxy","containerImage":"quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:918f311769d35d35ef5ffdc889b406eb1a8591de0fe9c009916c9218f6a9d94b","source":{"git":{"url":"https://github.com/openshift-pipelines/operator","revision":"570bcfb8310348417e9189f59dd1308f594ca76d","dockerfileUrl":"openshift/dockerfiles/proxy.Dockerfile"}}},{"name":"operator-main-webhook","containerImage":"quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:45b3f9a54e8937994efc20565fa7fa3e207619f5d247180683c34a021fff6a67","source":{"git":{"url":"https://github.com/openshift-pipelines/operator","revision":"570bcfb8310348417e9189f59dd1308f594ca76d","dockerfileUrl":"openshift/dockerfiles/webhook.Dockerfile"}}}],"artifacts":{}}'
        type: string
      - description: Namespace where the the Operator bundle will be deployed.
        name: NAMESPACE
        default: openshift-operators
        type: string
    tasks:
      - name: parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/integration-examples
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/test_metadata.yaml
        params:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
      - name: deploy-operator
        params:
          - name: bundleImage
            value: "$(tasks.parse-metadata.results.component-container-image)"
          - name: namespace
            value: "$(params.NAMESPACE)"
        taskSpec:
          params:
            - name: bundleImage
              type: string
            - name: namespace
              type: string
          volumes:
            - name: credentials
              secret:
                secretName: rosa
          steps:

            - name: operator-sdk-run-bundle
              image: quay.io/operator-framework/operator-sdk:latest
              env:
                - name: KUBECONFIG
                  value: "/credentials/kubeconfig"
              args:
                - run
                - bundle
                - --namespace
                - "$(params.namespace)"
                - "$(params.bundleImage)"
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
      - name: e2e-test
        description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
        runAfter:
          - deploy-operator
        params:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
        taskSpec:
          params:
            - name: SNAPSHOT
          volumes:
            - name: credentials
              secret:
                secretName: rosa
          results:
            - name: TEST_OUTPUT
              description: Test output
          steps:
            - name: e2e
              image: quay.io/openshift-pipeline/ci:latest
              env:
                - name: SNAPSHOT
                  value: $(params.SNAPSHOT)
                - name: KUBECONFIG
                  value: "/credentials/kubeconfig"
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
              script: |
                #!/usr/bin/env bash
                set -ex -u -o pipefail

                echo "KUBECONFIG : $KUBECONFIG"
                git clone https://github.com/openshift-pipelines/release-tests.git
                gauge run --tags="" --log-level=debug --verbose release-tests/specs/pipelines
