apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pbindal-pipelines-e2e-tests-
  labels:
    appstudio.openshift.io/component: operator-main-bundle
spec:
  params:
    - name: SNAPSHOT
      value: { "application": "operator-main","components": [ { "name": "operator-main-bundle","containerImage": "quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle@sha256:8d7cc312acac727cc9936484c0ee5fbb8f6c59e4d18a91cacb2a7d8d08596954","source": { "git": { "url": "https://github.com/openshift-pipelines/operator","revision": "6f07a90d8e9c37385d12eda2fc1693a52dbe7e4c" } } },{ "name": "operator-main-index","containerImage": "quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main-index@sha256:f139167fc6ceb65398ce62af7fcb169e516b041e5a28d4f9f65fc4f9edf02302","source": { "git": { "url": "https://github.com/openshift-pipelines/operator.git","revision": "cd5465c75587af9289c0e2101973eaf84f74202f","dockerfileUrl": "olm-catalog/openshift-pipelines/index/Dockerfile" } } },{ "name": "operator-main-operator","containerImage": "quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/operator@sha256:b46aa2b1500b908d4f563dadd599a72e943eebca97549fdafd82d0e3b6a03557","source": { "git": { "url": "https://github.com/openshift-pipelines/operator","revision": "56310e8ef02b0eafd96a3c7b6e2b978085317388","dockerfileUrl": "openshift/dockerfiles/operator.Dockerfile" } } },{ "name": "operator-main-proxy","containerImage": "quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/proxy@sha256:c60e96dcbd15b4558f47be9e11d9a2489fb7eaf0c400b5b8a16b2e50974dd521","source": { "git": { "url": "https://github.com/openshift-pipelines/operator","revision": "56310e8ef02b0eafd96a3c7b6e2b978085317388","dockerfileUrl": "openshift/dockerfiles/proxy.Dockerfile" } } },{ "name": "operator-main-webhook","containerImage": "quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/webhook@sha256:6976a93122b5aa0ff1186325622ecb760b7e0bee30a6e7f4b9cb357db6afb122","source": { "git": { "url": "https://github.com/openshift-pipelines/operator","revision": "56310e8ef02b0eafd96a3c7b6e2b978085317388","dockerfileUrl": "openshift/dockerfiles/webhook.Dockerfile" } } } ],"artifacts": { } }
  pipelineRef:
    resolver: git
    params:
      - name: name
        value: e2e-tests-tektoncd-pipelines
      - name: url
        value: https://github.com/pramodbindal/demo
      - name: revision
        value: main
      - name: pathInRepo
        value: e2e/pipeline/e2e-tektoncd-pipeline.yaml

