---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tektoncd-pipelines-e2e-tests-
spec:
  PipelineSpec:
    params:
      - description: Snapshot of the application
        name: SNAPSHOT
        default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
        type: string
      - description: Namespace where the the Operator bundle will be deployed.
        name: NAMESPACE
        default: default
        type: string
    tasks:
      - name: deploy-operator
        params:
          - name: bundleImage
#            value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle:on-pr-50f60424789114acc5c6644cbea516e475c439d0
            value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-main/bundle@sha256:d4c74d2cc0a790f90be144beb2702abfc6a1fd106a2de8aa0ab0604ac3112046
          - name: namespace
            value: "$(params.NAMESPACE)"
        taskSpec:
          params:
            - name: bundleImage
              type: string
            - name: namespace
              type: string
          volumes:
            - name: credentials
              secret:
                secretName: k8s-rosa
          steps:

            - name: operator-sdk-run-bundle
              image: quay.io/operator-framework/operator-sdk:latest
              env:
                - name: KUBECONFIG
                  value: "/credentials/rosa"
              args:
                - run
                - bundle
                - --namespace
                - "$(params.namespace)"
                - "$(params.bundleImage)"
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
#              script: |
#                set -x
#                echo  "KUBECONFIG : $KUBECONFIG"
#                ls -l /credentials
#                pwd
#                cat $KUBECONFIG
