#!/bin/bash

export KUBE_HOME=~/RedHat/kube/
export KUBECONFIG=/tmp/eaas-kubeconfig
export INSECURE_SKIP_TLS_VERIFY=true
export CLUSTER_KUBECONFIG=/tmp/CLUSTER-kubeconfig

cat $KUBE_HOME/konflux > $KUBECONFIG

EAAS=$1
#EAAS=openshift-e357f2c64ddd06b28d1be4e1d7e9e644-provision-eaas-space-secret

oc get secret $EAAS -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
cat $CLUSTER_KUBECONFIG > $KUBECONFIG

PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')

echo "Cluster Phase : $PHASE"

while [ $PHASE = "ClusterInstalling" ];
do
  oc get cti
  sleep 30
  PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')
done
oc get cti -o yaml

SECRET=$(oc get cti -o jsonpath='{.items[0].status.kubeconfig.name}')
echo "Found kubeconfig secret: $SECRET"

oc get secret $SECRET -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
echo "Wrote kubeconfig to $CLUSTER_KUBECONFIG"
cat $CLUSTER_KUBECONFIG > $KUBECONFIG
#oc projects

