#!/bin/bash

set -x

export KUBECONFIG=$KUBE_HOME/eaas-kubeconfig
export INSECURE_SKIP_TLS_VERIFY=true
export CLUSTER_KUBECONFIG=$KUBE_HOME/CLUSTER-kubeconfig

cat $KUBE_HOME/konflux > $KUBECONFIG

EAAS=eaas-spacerequest-x5zp6-2x9ck

oc get secret $EAAS -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
cat $CLUSTER_KUBECONFIG > $KUBECONFIG

PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')

echo "Cluster Phase : $PHASE"

while [ $PHASE = "ClusterInstalling" ];
do
  oc get cti
  sleep 30
  PHASE=$(oc get cti -o jsonpath='{.items[0].status.phase}')
done

SECRET=$(oc get cti -o jsonpath='{.items[0].status.kubeconfig.name}')
echo "Found kubeconfig secret: $SECRET"

oc get secret $SECRET -o go-template --template="{{.data.kubeconfig|base64decode}}" > $CLUSTER_KUBECONFIG
echo "Wrote kubeconfig to $CLUSTER_KUBECONFIG"
cat $CLUSTER_KUBECONFIG > $KUBECONFIG


oc projects


