---
name: Update rpms for konflux build

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 06:00.
  workflow_dispatch: # Manual workflow trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
#    - uses: actions/setup-go@v5
#      with:
#        go-version: 1.23.x
    - id: set-matrix
      run: |
        sudo apt install python3-dnf skopeo  -y
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
