---
name: Update rpms for konflux build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 6 * * *" # Daily at 06:00.
  workflow_dispatch: # Manual workflow trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get -y install podman
    - run: |
        BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest
        podman run --rm\
          -e BASE_IMAGE=$BASE_IMAGE \
          -v ./rpms:/rpms -w /rpms -it  $BASE_IMAGE  sh -c "
            cat /etc/yum.repos.d/ubi.repo > ./ubi.repo
            microdnf install -y python3-dnf skopeo pip          
            python -m pip install https://github.com/konflux-ci/rpm-lockfile-prototype/archive/refs/tags/v0.13.1.tar.gz
            rpm-lockfile-prototype --image $BASE_IMAGE ./rpms.in.yaml
          "
